### DISCUSSION TITLE
Support release/publish jar to maven repository

### DISCUSSION THREAD

**Discussion by emmansun** [jolt-community/jolt-community#23] [Ideas]
Support to publish this community version to maven repository.

1. account and setup
2. jar name? default is jolt-community
3. version. 0.1.9?

### Reference:
[Publish your artifact to the Maven Central Repository using GitHub Actions](https://medium.com/@jtbsorensen/publish-your-artifact-to-the-maven-central-repository-using-github-actions-15d3b5d9ce88)

- [x] secrets for CENTRAL_TOKEN_USERNAME / CENTRAL_TOKEN_PASSWORD / GPG_SIGNING_KEY / GPG_SIGNING_KEY_PASSWORD.
- [x] align groupId with namespace.
- [x] align release processes.
- [x] update pom.xml to support release.
- [x] add workflows to support release.
- [x] test release

**Comment by riccardocossu** [comment]
I am quite interested in this; maybe I can help, I published a few lbraries/tools in the past; we may want to use this fork on our project

**Comment by bobeal** [comment]
@riccardocossu sure, feel free to contribute :)

before that, we'll have to decide on the new packaging name (see discussion going on in https://github.com/orgs/jolt-community/discussions/4)

**Comment by bobeal** [comment]
A follow up on this:
- New packaging is done (https://github.com/jolt-community/jolt-community/pull/16)
- Jars are currently named `jolt-{module}-{version}.jar`. For consistency and to avoid confusion, we could rename them to `jolt-community-{module}-{version}.jar`
- About the version... maybe we could jump to 1.0.0 to emphasize this is a full refresh?

**Comment by emmansun** [comment]
so, can we start this task?

**Comment by bobeal** [comment]
Yes, I think we can.

I can do the part about the renaming of the jars and bumping the version number.

Someone volunteers for the publication of the jars on Maven repository?

**Comment by emmansun** [comment]
Hi @riccardocossu can you help it?

**Comment by emmansun** [comment]
We can create `io.github.jolt-community` namespace with some extra steps to pass verification.

<img width="569" height="336" alt="Image" src="https://github.com/user-attachments/assets/b3d437ce-7519-4b49-a02c-8e691b035575" />

**Comment by emmansun** [comment]
But when i try to create namespace `io.joltcommunity`:

<img width="570" height="293" alt="Image" src="https://github.com/user-attachments/assets/f9ce26f3-c904-49d2-bbbc-0d044e935272" />

Hi @bobeal , it seems we can't use this namespace.

**Comment by riccardocossu** [comment]
@emmansun the main point is that we will have to create an account on maven central; maybe in the name of one of us, but I don't know if it's a good idea going forward. Also we will need to manage who's gonna hold the signing keys (signing of the artifacts is mandatory on maven central)

**Comment by emmansun** [comment]
@riccardocossu yes, we need an account who is the owner of this repository.

**Comment by bobeal** [comment]
@emmansun you were already admin of this repository (the highest role). You are also now owner of the organisation.

**Comment by emmansun** [comment]
> [@emmansun](https://github.com/emmansun) you were already admin of this repository (the highest role). You are also now owner of the organisation.

I can only register namespace `io.github.jolt-community` namespace, we have no domain of `www.joltcommunity.io`. So do not know if we can publish jar with group-id `io.joltcommunity.jolt`. It seems we need to change the groupId to `io.github.jolt-community`, any concern?

<img width="438" height="109" alt="Image" src="https://github.com/user-attachments/assets/c546af2c-709c-41ff-bdf2-59b894563133" />

<img width="965" height="230" alt="Image" src="https://github.com/user-attachments/assets/730cd701-4e3e-4ca2-a3ef-e8212276a31a" />

**Reply by bobeal** [reply]
If it is only about changing the group id (and not all the package names), that's fine for me.

**Reply by emmansun** [reply]
If you change the `groupId` to `io.github.jolt-community.jolt`, it is recommended to update the Java package names in your code to match the new `groupId`. This ensures consistency between the Maven configuration and the Java code structure, following best practices for naming conventions.

Of course, keep current package name `io.joltcommunity.jolt` should be ok.

**Comment by emmansun** [comment]
We have mainly 2 code branches now: **develop** and **master**, what's a light weight release/publish process for us?

1. **PRE-RELEASE**: create a PR to sync code form **develop** to **master**, and merge the latest code to master; **make assumption we have updated related version information in pom.xml**.
2. **RELEASE**: create a new release on **master**, trigger a release workflow (github action), upload asset (jar and javadoc?).
3. **PUBLISH**: publish to maven central repository.

Steps 2,3 maybe in same workflow, below workflow was generated by AI.
```yml
name: Release and Publish to Maven Central

on:
  release:
    types:
      - created

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: maven
        settings-path: ${{ github.workspace }}

    - name: Import GPG key
      run: |
        echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --import
        gpg --list-keys
      env:
        GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

    - name: Configure Maven settings
      run: |
        echo "<settings>
          <servers>
            <server>
              <id>maven</id>
              <username>${{ secrets.MAVEN_USERNAME }}</username>
              <password>${{ secrets.MAVEN_PASSWORD }}</password>
            </server>
          </servers>
          <profiles>
            <profile>
              <id>gpg</id>
              <properties>
                <gpg.executable>gpg</gpg.executable>
                <gpg.passphrase>${{ secrets.GPG_PASSPHRASE }}</gpg.passphrase>
              </properties>
            </profile>
          </profiles>
        </settings>" > ${{ github.workspace }}/settings.xml

    - name: Build and deploy all modules
      run: mvn clean deploy -DskipTests -P gpg --settings ${{ github.workspace }}/settings.xml

    - name: Upload Release Assets
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: |
          jolt-core/target/*.jar
          json-utils/target/*.jar
          cli/target/*.jar
          guice/target/*.jar
          complete/target/*.jar
        asset_name: jolt-${{ github.event.release.tag_name }}-${{ github.job }}.jar
        asset_content_type: application/java-archive
```

Of course, there will be update and also related pom.xml update. 

@bobeal @riccardocossu , pls review and advise it.

**Reply by bobeal** [reply]
About asset name, isn't it jolt-${{ github.job }}-${{ github.event.release.tag_name }}.jar instead?

There is also a `json-utils/json-utils-{version}.jar` that is published on Maven repository (https://mvnrepository.com/artifact/com.bazaarvoice.jolt/json-utils). Maybe it could be renamed to `jolt-community-json-utils-...`?

Otherwise, LGTM.

**Comment by emmansun** [comment]
> [@emmansun](https://github.com/emmansun) the main point is that we will have to create an account on maven central; maybe in the name of one of us, but I don't know if it's a good idea going forward. Also we will need to manage who's gonna hold the signing keys (signing of the artifacts is mandatory on maven central)

for the signing key, due to we will upload the private key and password to github security env. so i think it's not an issue, anyone of the project/repo owners can check it.

I will use below user id to generate signing key:

> Real name: jolt community
> Email address: jolt-community@github.com
> You selected this USER-ID:
>     "jolt community <jolt-community@github.com>"

any concern?

**Reply by emmansun** [reply]
<img width="957" height="289" alt="image" src="https://github.com/user-attachments/assets/7915ae10-242d-40bf-85b6-569c0820dac4" />

> sec   ed25519/4256812F668C8052 2025-07-15 [SC] [expires: 2028-07-14]
>       2ED6520ED3661A73699BD7BF4256812F668C8052

**Comment by riccardocossu** [comment]
@emmansun I never did it with github action (I used to do it back in the days on my local machine), but the reciper sounds good; it has the required steps, but we will also need the maven gpg plugin:

https://maven.apache.org/plugins/maven-gpg-plugin/sign-and-deploy-file-mojo.html

others than that we may wanna add gpg commits signing like described here, that can be configured on the developer machines, but it should also be done for the commits of the files that may be created during deploy preparation (for example if we use the maven release plugin): 
https://gist.github.com/SingingBush/2bab7e8e8eb3dfbe8bd0fd7ff7606fba

**Reply by emmansun** [reply]
Yes, this workflow requires Maven plugins to work correctly. Specifically:

1. **Maven GPG Plugin**: To sign artifacts with GPG, you need the `maven-gpg-plugin` configured in your `pom.xml`. This plugin ensures that the artifacts are signed before deployment.

2. **Maven Deploy Plugin**: The `maven-deploy-plugin` is responsible for deploying the signed artifacts to the Maven Central repository.

3. **Maven Release Plugin** (optional): If you are managing releases, this plugin can help automate versioning and tagging.

Here is an example configuration for the `maven-gpg-plugin` and `maven-deploy-plugin` in your `pom.xml`:

```xml
<build>
    <plugins>
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-gpg-plugin</artifactId>
            <version>3.0.1</version>
            <executions>
                <execution>
                    <id>sign-artifacts</id>
                    <phase>verify</phase>
                    <goals>
                        <goal>sign</goal>
                    </goals>
                </execution>
            </executions>
        </plugin>
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-deploy-plugin</artifactId>
            <version>3.0.0</version>
        </plugin>
    </plugins>
</build>
```

Ensure these plugins are properly configured in your `pom.xml` for the workflow to function as expected.

Let's align release/deploy process first. Maybe we also need a special version for test.

**Comment by emmansun** [comment]
### Updated Release Processes:

1. Freeze changes to the develop branch and agree to release a new version;
2. Sync code to **master** branch from **develop** branch;
3. Create a new release with release notes and a release **tag**;
4. Trigger release/deploy workflow, this workflow will use `mvn versions:set -DnewVersion=${{ github.event.release.tag_name }}` to update the versions in pom.xml, and push the update to `master`, this process is complex due to the new tag was created via release creation, and we hope to include the updated pom.xml into this release tag.
5. Sync back code to **develop** branch from **master** branch.

below is the part of workflow generated by AI, which is used to handle version update and release tag update:
```yaml
- name: Set version
  run: mvn versions:set -DnewVersion=${{ github.event.release.tag_name }}

- name: Commit version change
  run: |
    git config user.name "GitHub Actions"
    git config user.email "actions@github.com"
    git add **/pom.xml
    git commit -m "Update version to ${{ github.event.release.tag_name }}"
    git push

- name: Delete existing tag
  run: |
    git tag -d ${{ github.event.release.tag_name }}
    git push origin :refs/tags/${{ github.event.release.tag_name }}

- name: Create and push updated tag
  run: |
    git tag ${{ github.event.release.tag_name }}
    git push origin ${{ github.event.release.tag_name }}
```
The `mvn versions:set` command will set the version in the `pom.xml` exactly as provided in the `-DnewVersion` parameter. If the `tag_name` includes the `v` prefix (e.g., `v1.0.0`), it will set the version in the `pom.xml` to `v1.0.0`, which is not the expected format for Maven versions.

To remove the `v` prefix before setting the version, you can use a shell command to strip it. Here's an updated step:

```yaml
- name: Set version
  run: |
    VERSION=${{ github.event.release.tag_name }}
    CLEAN_VERSION=${VERSION#v}
    mvn versions:set -DnewVersion=$CLEAN_VERSION
``` 

### Explanation:
1. `VERSION=${{ github.event.release.tag_name }}`: Captures the release tag name.
2. `CLEAN_VERSION=${VERSION#v}`: Removes the `v` prefix if present.
3. `mvn versions:set -DnewVersion=$CLEAN_VERSION`: Sets the cleaned version in the `pom.xml`.
4. 
**Steps 2** :
```yaml
name: Pre-Release Sync

on:
  workflow_dispatch: # Manual trigger

jobs:
  sync-branches:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout develop branch
      uses: actions/checkout@v3
      with:
        ref: develop

    - name: Configure Git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

    - name: Merge develop into master
      run: |
        git fetch origin master
        git checkout master
        git merge develop --no-ff
        git push origin master
```

**Step 5:**
```yaml
name: Post-Release Sync

on:
  workflow_dispatch: # Manual trigger

jobs:
  sync-branches:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout master branch
      uses: actions/checkout@v3
      with:
        ref: master

    - name: Configure Git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

    - name: Merge master into develop
      run: |
        git fetch origin develop
        git checkout develop
        git merge master --no-ff
        git push origin develop
```

We can publish one beta release for test.

@bobeal @riccardocossu Any suggestion or concern? I have no experience either. Take Opentelemetry Java project as sample, it typically follows a structured release and branching strategy to ensure stability and maintainability. Here are the details:

### Branching Strategy:
1. **Main Branch (`main`)**:
   - The primary development branch.
   - Contains the latest code changes and features under development.
   - May include breaking changes or experimental features.

2. **Release Branches (`release/*`)**:
   - Created for specific releases (e.g., `release/v1.0.0`).
   - Used to stabilize and finalize a release.
   - Only critical bug fixes and release-specific changes are merged into these branches.

3. **Feature Branches (`feature/*`)**:
   - Created for individual features or enhancements.
   - Merged into `main` after review and testing.

5. **Hotfix Branches (`hotfix/*`)**:
   - Created for urgent fixes to a released version.
   - Merged into both the relevant release branch and `main`.

### Release Strategy:
1. **Versioning**:
   - Follows [Semantic Versioning](https://semver.org/) (e.g., `1.0.0`, `1.1.0`, `2.0.0`).
   - Major versions include breaking changes.
   - Minor versions add features in a backward-compatible manner.
   - Patch versions include bug fixes.

2. **Release Process**:
   - Code is stabilized in a release branch.
   - Pre-release versions (e.g., `1.0.0-RC1`) may be published for testing.
   - Final release is tagged (e.g., `v1.0.0`) and published to Maven Central.

3. **Tagging**:
   - Each release is tagged in the repository (e.g., `v1.0.0`).
   - Tags are immutable and represent the exact state of the code for the release.

4. **Changelog**:
   - Maintains a detailed changelog for each release.
   - Includes new features, bug fixes, and breaking changes.

6. **Backward Compatibility**:
   - Ensures backward compatibility for minor and patch releases.
   - Breaking changes are introduced only in major releases.

This strategy ensures a clear separation of development, stabilization, and release processes while maintaining high-quality standards.

**Reply by bobeal** [reply]
I fully agree with most of the points here.

Only a few comments:
- before we finalize the release process, we could rename `master` to `main`
- not sure we'll need release branches. it is typically used in big projects with many new features and bug fixes in each release. let's how it goes.
- for the release notes, I typically use https://github.com/release-drafter/release-drafter which is very convenient. I can prepare a PR to add it

**Reply by emmansun** [reply]
> I fully agree with most of the points here.
> 
> Only a few comments:
> 
> * before we finalize the release process, we could rename `master` to `main`
> * not sure we'll need release branches. it is typically used in big projects with many new features and bug fixes in each release. let's how it goes.
> * for the release notes, I typically use https://github.com/release-drafter/release-drafter which is very convenient. I can prepare a PR to add it

yes, for release branch, it's the practice for most of big projects.

**Reply by emmansun** [reply]
updated the branch master to main.

**Comment by emmansun** [comment]
https://github.com/jolt-community/jolt-community/actions/runs/16558541943/job/46823799003
```
remote: error: GH006: Protected branch update failed for refs/heads/main.        
remote: 
remote: - This branch must not contain merge commits.        
remote:   Found 1 violation:        
remote: 
remote:   5f0b1b19dc22494370e8c980a851485137fb7a16        
remote: 
remote: - Changes must be made through a pull request.        
To https://github.com/jolt-community/jolt-community
 ! [remote rejected] main -> main (protected branch hook declined)
error: failed to push some refs to 'https://github.com/jolt-community/jolt-community'
Error: Process completed with exit code 1.
```

The `main` branch's current protection rules make it unsuitable for direct updates or automated workflows like the one in your `.github/workflows/pre-release.yml`. Specifically:

1. **No Merge Commits**: The workflow uses `git merge`, which creates merge commits, violating the branch protection rule.
2. **Pull Request Requirement**: The workflow directly pushes to `main`, which is not allowed under the branch protection rules.

To use the `main` branch for releases, you can:
- Adjust the branch protection rules to allow merge commits and direct pushes from the workflow.
- Modify the workflow to create a pull request instead of directly merging and pushing.

It seems both `develop` and `main` branches require PR, we need to update the release scripts.

**Comment by emmansun** [comment]
### Simplify the release workflows as below:

1. Confirm to release.
2. Backup the draft release notes.
3. Update version to pom.xml (all modules), this step is optional if the version had been updated as expected, otherwise trigger the workflow and input version manually.
4. Sync code from `develop` to `main`.
5. Create a release and publish it (**make sure the tag is aligned with the version in pom.xml**, for example, if the version is `1.0.0`, then the tag should be `v1.0.0`), this will trigger the workflow to publish the assets to maven central repository.

BTW, it seems the `--- dependency-check:12.1.3:check (default) @ jolt-community-parent ---` this step took a long time:
```
Warning:  An NVD API Key was not provided - it is highly recommended to use an NVD API key as the update can take a VERY long time without an API Key
[INFO] NVD API has 303,771 records in this update
[INFO] Downloaded 10,000/303,771 (3%)
[INFO] Downloaded 20,000/303,771 (7%)
[INFO] Downloaded 30,000/303,771 (10%)
[INFO] Downloaded 40,000/303,771 (13%)
[INFO] Downloaded 50,000/303,771 (16%)
[INFO] Downloaded 60,000/303,771 (20%)
```

**Reply by emmansun** [reply]
Publish failed:

```
Error:  
Deployment bd401977-c021-4881-9df7-744756164b8f failed
pkg:maven/io.github.jolt-community.jolt/jolt-community-complete@1.0.0-beta.9:
 - Project description is missing
 - Project URL is not defined
 - Developers information is missing
pkg:maven/io.github.jolt-community.jolt/jolt-community-core@1.0.0-beta.9:
 - Project description is missing
 - Project URL is not defined
 - Developers information is missing
pkg:maven/io.github.jolt-community.jolt/jolt-community-guice@1.0.0-beta.9:
 - Project description is missing
 - Project URL is not defined
 - Developers information is missing
pkg:maven/io.github.jolt-community.jolt/jolt-community@1.0.0-beta.9:
 - Project description is missing
 - Project URL is not defined
 - Developers information is missing
pkg:maven/io.github.jolt-community.jolt/jolt-community-cli@1.0.0-beta.9:
 - Project description is missing
 - Project URL is not defined
 - Developers information is missing
pkg:maven/io.github.jolt-community.jolt/json-community-utils@1.0.0-beta.9:
 - Project description is missing
 - Project URL is not defined
 - Developers information is missing
pkg:maven/io.github.jolt-community.jolt/jolt-community-parent@1.0.0-beta.9:
 - Project description is missing
 - Project URL is not defined
 - Developers information is missing
 ```

**Comment by emmansun** [comment]
Hi All,

Start to sync code from `develop` to `main`, any concern?

**Reply by bobeal** [reply]
Go! :)

**Reply by emmansun** [reply]
Hi @bobeal , pls enable workflow to create PR, thx!

<img width="939" height="399" alt="image" src="https://github.com/user-attachments/assets/9eae2855-0d5f-41b0-84f3-d8e060180276" />

**Reply by emmansun** [reply]
done by myself

**Reply by bobeal** [reply]
The checkbox is also disabled for me...

**Reply by bobeal** [reply]
ah. good then.

**Reply by emmansun** [reply]
It seems we can't use the release drafter on main `branch` directly. I also did NOT backup the old one.

<img width="1214" height="581" alt="image" src="https://github.com/user-attachments/assets/cad8c3ee-1e75-486a-8ebe-583479f8a703" />

**Reply by emmansun** [reply]
Hi @bobeal ,

Let's limit the release drafter to `develop` branch only?

``` yaml
name: Release Drafter

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - develop
```
