### ISSUE TITLE
Support release/publish jar to maven repository

### ISSUE THREAD

**Issue by emmansun** [jolt-community/jolt-community#3]
Support to publish this community version to maven repository.

1. account and setup
2. jar name? default is jolt-community
3. version. 0.1.9?

**Comment by bobeal** [comment]
@riccardocossu sure, feel free to contribute :)

before that, we'll have to decide on the new packaging name (see discussion going on in https://github.com/orgs/jolt-community/discussions/4)

**Comment by bobeal** [comment]
A follow up on this:
- New packaging is done (https://github.com/jolt-community/jolt-community/pull/16)
- Jars are currently named `jolt-{module}-{version}.jar`. For consistency and to avoid confusion, we could rename them to `jolt-community-{module}-{version}.jar`
- About the version... maybe we could jump to 1.0.0 to emphasize this is a full refresh?

**Comment by bobeal** [comment]
Yes, I think we can.

I can do the part about the renaming of the jars and bumping the version number.

Someone volunteers for the publication of the jars on Maven repository?

**Comment by emmansun** [comment]
Hi @riccardocossu can you help it?

**Comment by emmansun** [comment]
<img width="569" height="336" alt="Image" src="https://github.com/user-attachments/assets/b3d437ce-7519-4b49-a02c-8e691b035575" />

**Comment by emmansun** [comment]
But when i try to create namespace `io.joltcommunity`:

<img width="570" height="293" alt="Image" src="https://github.com/user-attachments/assets/f9ce26f3-c904-49d2-bbbc-0d044e935272" />

**Comment by riccardocossu** [comment]
@emmansun the main point is that we will have to create an account on maven central; maybe in the name of one of us, but I don't know if it's a good idea going forward. Also we will need to manage who's gonna hold the signing keys (signing of the artifacts is mandatory on maven central)

**Comment by bobeal** [comment]
@emmansun you were already admin of this repository (the highest role). You are also now owner of the organisation.

**Comment by emmansun** [comment]
We have mainly 2 code branches now: **develop** and **master**, what's a light weight release/publish process for us?

1. **PRE-RELEASE**: create a PR to sync code form **develop** to **master**, and merge the latest code to master; **make assumption we have updated related version information in pom.xml**.
2. **RELEASE**: create a new release on **master**, trigger a release workflow (github action), upload asset (jar and javadoc?).
3. **PUBLISH**: publish to maven central repository.

Steps 2,3 maybe in same workflow, below workflow was generated by AI.
```yml
name: Release and Publish to Maven Central

on:
  release:
    types:
      - created

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: maven
        settings-path: ${{ github.workspace }}

    - name: Import GPG key
      run: |
        echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --import
        gpg --list-keys
      env:
        GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

    - name: Configure Maven settings
      run: |
        echo "<settings>
          <servers>
            <server>
              <id>maven</id>
              <username>${{ secrets.MAVEN_USERNAME }}</username>
              <password>${{ secrets.MAVEN_PASSWORD }}</password>
            </server>
          </servers>
          <profiles>
            <profile>
              <id>gpg</id>
              <properties>
                <gpg.executable>gpg</gpg.executable>
                <gpg.passphrase>${{ secrets.GPG_PASSPHRASE }}</gpg.passphrase>
              </properties>
            </profile>
          </profiles>
        </settings>" > ${{ github.workspace }}/settings.xml

    - name: Build and deploy all modules
      run: mvn clean deploy -DskipTests -P gpg --settings ${{ github.workspace }}/settings.xml

    - name: Upload Release Assets
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: |
          parent/target/*.jar
          jolt-core/target/*.jar
          json-utils/target/*.jar
          cli/target/*.jar
          guice/target/*.jar
          complete/target/*.jar
        asset_name: jolt-${{ github.event.release.tag_name }}-${{ github.job }}.jar
        asset_content_type: application/java-archive
```

Of course, there will be update and also related pom.xml update.

@bobeal @riccardocossu , pls review and advise it.
